# Generated by Django 6.0.5 on 2026-07-01 08:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_date', models.DateField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('partial', 'Partial (some questions failed)'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('llm_provider_used', models.CharField(blank=True, max_length=50)),
                ('search_queries_used', models.JSONField(blank=True, default=list)),
                ('questions_generated', models.PositiveSmallIntegerField(default=0)),
                ('questions_rejected_duplicate', models.PositiveSmallIntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-run_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyInterviewQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('category', models.CharField(choices=[('ml_fundamentals', 'ML Fundamentals'), ('stats', 'Statistics / Probability'), ('system_design', 'ML/GenAI System Design'), ('coding', 'Coding / Algorithms'), ('behavioral', 'Behavioral / Case Study'), ('genai', 'GenAI / LLM Specific')], db_index=True, max_length=30)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, max_length=10)),
                ('company_style', models.CharField(blank=True, max_length=100)),
                ('model_answer', models.TextField()),
                ('follow_up_questions', models.JSONField(blank=True, default=list)),
                ('source_context', models.TextField(blank=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('date_generated', models.DateField(auto_now_add=True, db_index=True)),
                ('times_shown', models.PositiveIntegerField(default=0)),
                ('user_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interview_prep.generationrun')),
            ],
            options={
                'ordering': ['-date_generated'],
                'indexes': [models.Index(fields=['date_generated', 'category'], name='interview_p_date_ge_7093a1_idx')],
            },
        ),
    ]
