# Generated by Django 6.0.5 on 2026-07-01 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('company_type', models.CharField(choices=[('IT_SERVICES', 'IT Services'), ('PRODUCT', 'Product'), ('CORE', 'Core / Manufacturing'), ('FINANCE', 'Finance / Consulting'), ('STARTUP', 'Startup'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('career_portal_base_url', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HiringSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('opportunity_type', models.CharField(choices=[('INTERNSHIP', 'Internship'), ('FULL_TIME', 'Full-Time'), ('HACKATHON', 'Hackathon'), ('OA', 'Online Assessment'), ('GRAD_PROGRAM', 'Graduate Program')], max_length=20)),
                ('recurrence_pattern', models.CharField(choices=[('ANNUAL', 'Annual'), ('BIANNUAL', 'Twice a year'), ('IRREGULAR', 'Irregular')], default='ANNUAL', max_length=20)),
                ('typical_window_start_month', models.PositiveSmallIntegerField()),
                ('typical_window_end_month', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_seasons', to='hiring_tracker.company')),
            ],
            options={
                'ordering': ['company__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('opportunity_type', models.CharField(choices=[('INTERNSHIP', 'Internship'), ('FULL_TIME', 'Full-Time'), ('HACKATHON', 'Hackathon'), ('OA', 'Online Assessment'), ('GRAD_PROGRAM', 'Graduate Program')], max_length=20)),
                ('expected_registration_start', models.DateField(blank=True, null=True)),
                ('expected_registration_end', models.DateField(blank=True, null=True)),
                ('expected_hiring_window_start', models.DateField()),
                ('expected_hiring_window_end', models.DateField()),
                ('career_portal_link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('priority_level', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('REGISTRATION_OPEN', 'Registration Open'), ('APPLY_NOW', 'Apply Now'), ('OA_EXPECTED', 'OA Expected'), ('INTERVIEW_PHASE', 'Interview Phase'), ('CLOSED', 'Closed'), ('MISSED', 'Missed')], default='UPCOMING', max_length=20)),
                ('source', models.CharField(choices=[('SEED', 'Pre-seeded calendar data'), ('SCRAPER', 'Automated scraper'), ('MANUAL', 'Manually added')], default='SEED', max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('is_date_confirmed', models.BooleanField(default=False, help_text='False if dates are projected from typical pattern, True if confirmed via official source/scraper.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='hiring_tracker.company')),
                ('hiring_season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='hiring_tracker.hiringseason')),
            ],
            options={
                'ordering': ['expected_hiring_window_start'],
                'indexes': [models.Index(fields=['expected_hiring_window_start'], name='hiring_trac_expecte_ed4eb0_idx'), models.Index(fields=['status'], name='hiring_trac_status_9b6639_idx'), models.Index(fields=['opportunity_type'], name='hiring_trac_opportu_74eac5_idx')],
            },
        ),
    ]
