# Generated by Django 6.0.5 on 2026-06-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingprofile',
            name='freeze_tokens',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='codingprofile',
            name='last_freeze_reset_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='journal_entry',
            field=models.TextField(blank=True, default=''),
        ),
    ]
