# Generated by Django 6.0.5 on 2026-06-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_codingprofile_freeze_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
