# Generated by Django 6.0.5 on 2026-06-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dailylog_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
